### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by nethip**
@pelatx I have made some code cleanup w.r.t your code. Please have a look at the code and let me know if there is anything that I am missing here.

### CODE REVIEW

**Comment by pelatx** [comment]
Thanks for the cleaning @nethip.

I have found some errors with these changes that happen in first execution (there is no `window.ini`):

- This error is printed and maybe it should not (in this first execution):
`Err -> SaveWindowState (): could not create a file object to read window.ini. Error Description: The file or directory does not exist.`

- If we demaximize Brackets, the window is very reduced (only the decoration of the window manager and the native menu can be seen).

- If we close Brackets when maximized, the console throws the errors:
`[0419/161916: ERROR: browser_main_loop.cc (261)] GLib: g_key_file_save_to_file: assertion 'error == NULL || * error == NULL 'failed`
`Err -> SaveWindowState (): could not write to window.ini. Error Description: The file or directory does not exist`

and the `window.ini` file is not created.


I am quite new contributing to projects. That's why I ask you how it is better to proceed. Do I merge this PR and work to solve this?
Or do I try to follow the cleaning guidelines of this PR on my original code so that you can consider it?

**Comment by nethip** [comment]
@pelatx thanks for pointing out. I will work on fixing them. Once updated I will ping you so that you can merge the changes into your fork’s branch.

**Comment by pelatx** [comment]
@nethip,

I have had some free time and I have been playing a bit with the code of this PR. Maybe you have already solved it. I hope you do not mind if I tell you what I found.

On the first issue I mention, I do not think it should be avoided. Because the only option I see is that there is no error message in any case. And it does not seem very good practice.

On the second: we just have to move this piece of code (from `LoadWindowState` function)
```
     gtk_window_move (GTK_WINDOW (window), left, top);
     gtk_window_set_default_size (GTK_WINDOW (window), width, height);

     if (maximized)
       MaximizeWindow (window);
```
outside the conditional where `g_key_file_load_from_file` is called.

And about the third one: I solved it by placing `err = NULL;` just before calling `g_key_file_save_to_file` in `SaveWindowState` function. But I confess that I do not fully understand why this works.

With these changes, the feature seems to work as expected.

Greetings.

**Comment by nethip** [comment]
@pelatx Absolutely right! I had made the changes yesterday but did not get a chance to update the branch. 

Could you try out the new changes?

**Comment by pelatx** [comment]
It looks and works perfect @nethip. Centering the window is a great addition.

I think it's better that you merge your branch directly because it differs and improves my original code a lot. I have no problem with that.

Edit: I made the mistake of test the code of your experimental branch. In this PR the second issue remains. 
I think we can fix it by moving some function calls out of the if block of g_key_file_load_from_file:
```
...
if (key_file && g_key_file_load_from_file(key_file, filePath, G_KEY_FILE_NONE, &err)) { 
  left = g_key_file_get_integer(key_file, "position", "left", &err); 
  if (!err) 
    top = g_key_file_get_integer(key_file, "position", "top", &err); 
  if (!err) 
    width = g_key_file_get_integer(key_file, "size", "width", &err); 
  if (!err) 
    height = g_key_file_get_integer(key_file, "size", "height", &err); 
  if (!err) 
    maximized = g_key_file_get_boolean(key_file, "state", "maximized", &err); 

  // If any value can not be readed, set defaults again 
  if (err) { 
    left = 1; 
    top = 1; 
    width = DEFAULT_WINDOW_WIDTH; 
    height = DEFAULT_WINDOW_HEIGHT; 
    maximized = TRUE; 
  } 
} else { 
  any_error = true; 
}

gtk_window_move(GTK_WINDOW(window), left, top); 
gtk_window_set_default_size(GTK_WINDOW(window), width, height); 

if (maximized) 
  MaximizeWindow(window); 
...
```

I have also used the code to center the window in SaveWindowState so that this remains in the next execution. What do you think about this?

**Comment by pelatx** [comment]
Thanks @nethip.

**Pull request merged**
